### ISSUE TITLE
no indication of sticker use

### ISSUE THREAD

**Issue by draeath** [smultar/discord.vdm#14]
when DM recipients reply with stickers, there is no indication this has been done.

Since sticker use is server membership and nitro dependent, it may not be possible to replicate the sticker - but it would still be useful to know that a sticker was sent, and if possible the name of the sticker.

This might also occur with messages containing only emoji.

**Comment by smultar** [comment]
Stickers aren't allowed to be posted via bots. So they are natively removed.

**Comment by draeath** [comment]
Hence:

>  but it would still be useful to know that a sticker was sent, and if possible the name of the sticker.

**Comment by smultar** [comment]
It's impossible to get sticker information from discord's API. As stickers aren't supposed to be saveable or reused.
